#!/usr/bin/env python3
"""Inline archcore.wasm (as base64) and its JS loader into arch-current.html.

The block lives between ARCHCORE:BEGIN/END markers placed just before the
page's main <script>; re-running replaces it in place.

Usage: python3 wasm/embed.py wasm/dist/archcore.wasm arch-current.html [wasm/js/archcore.js]
"""
import base64
import os
import pathlib
import sys

BEGIN = "<!-- ARCHCORE:BEGIN (generated by wasm/embed.py; do not edit by hand) -->"
END = "<!-- ARCHCORE:END -->"
# The main application script contains this line; the block goes right before
# the <script> tag that opens it (indentation varies across page versions).
ANCHOR = "const NEW_WORKSPACE_THUMBNAIL_BASE64"


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    wasm_path = pathlib.Path(sys.argv[1])
    html_path = pathlib.Path(sys.argv[2])
    glue_path = pathlib.Path(sys.argv[3]) if len(sys.argv) > 3 else pathlib.Path(__file__).with_name("js") / "archcore.js"

    wasm_b64 = base64.b64encode(wasm_path.read_bytes()).decode("ascii")
    # Wrap the base64 so the HTML stays editor-friendly.
    wrapped = "\n".join(wasm_b64[i:i + 160] for i in range(0, len(wasm_b64), 160))
    glue = glue_path.read_text(encoding="utf-8")
    # Kernel adapters register themselves on ArchCore.kernels.
    # ARCHCORE_KERNELS (space-separated names) restricts which adapters are
    # included, matching the kernels compiled into the wasm by build.sh.
    kernel_dir = glue_path.parent / "kernels"
    only = os.environ.get("ARCHCORE_KERNELS", "").split()
    kernels = sorted(kernel_dir.glob("*.js")) if kernel_dir.is_dir() else []
    if only:
        kernels = [k for k in kernels if k.stem in only]
    for kernel in kernels:
        glue += f"\n// ---- {kernel.name} ----\n" + kernel.read_text(encoding="utf-8")
    glue += (
        "\nArchCore.init();\n"
        "// Once the core is up, drop caches built by the JS paths so the next\n"
        "// frame is computed (and verified) through the wasm kernels.\n"
        "ArchCore.onReady((ok) => {\n"
        "    const engine = window.archInstance;\n"
        "    if (!ok || !engine) return;\n"
        "    try {\n"
        "        engine.clearPlotData();\n"
        "        if (engine.is3DMode) engine.recalculate3D();\n"
        "        engine.requestDraw();\n"
        "    } catch (e) { console.warn('[archcore] refresh failed', e); }\n"
        "});\n"
    )
    if "</script" in glue:
        raise SystemExit("glue must not contain </script")

    block = (
        f"{BEGIN}\n"
        f'<script type="application/wasm-base64" id="archcore-wasm">\n{wrapped}\n</script>\n'
        f"<script>\n{glue}</script>\n"
        f"{END}\n"
    )

    html = html_path.read_text(encoding="utf-8")
    start = html.find(BEGIN)
    if start >= 0:
        end = html.find(END, start)
        if end < 0:
            raise SystemExit("found ARCHCORE:BEGIN without ARCHCORE:END")
        end += len(END)
        if html[end:end + 1] == "\n":
            end += 1
        html = html[:start] + block + html[end:]
    else:
        line = html.find(ANCHOR)
        if line < 0:
            raise SystemExit("could not find the main-script anchor in " + str(html_path))
        anchor = html.rfind("<script", 0, line)
        if anchor < 0:
            raise SystemExit("could not find the <script> opening the main script in " + str(html_path))
        html = html[:anchor] + block + html[anchor:]

    html_path.write_text(html, encoding="utf-8")
    print(f"Embedded {wasm_path} ({len(wasm_b64)} base64 chars) into {html_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
